name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Generate Snake (Catppuccin Frappe)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: EthanBao27
          outputs: |
            dist/github-snake.svg?color_snake=#f4b8e4&color_dots=#303446,#414559,#51576d,#626880,#838ba7
            dist/github-snake-dark.svg?color_snake=#ffb6dc&color_dots=#2f3241,#3d4054,#505268,#65657c,#7c7e97
            dist/github-snake.gif?color_snake=#f4b8e4&color_dots=#303446,#414559,#51576d,#626880,#838ba7

      - name: Push generated files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}